### PR TITLE
Refactor Project Dialog Layout

### PR DESCRIPTION
**Pull request by krishnan-r**
Refactored project dialog layout using [CSS FlexBox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)

image

### CODE REVIEW

**Comment by omazapa** [comment]
investigating further the issue with the action,
I found that it was my problem, I tested it and fixed it in the PR #5

**Comment by diocas** [comment]
@krishnan-r great work, but I have some nit picking :) Hope you forgive me.

Can we... ?
- Make the project name bigger (to make the size comparable to the icon on the left)
- Remove the left padding on the project type options row (so that everything aligns on the left; the project icon maybe can also be moved more to the left)
- Make the borders of the text boxed/dropdown the same color? Preferably, the color of the dropdown. The border of the project name could be dimmer to be less noticeable, but I don't know if that makes it inconsistent.
- Make the icons on project type options row smaller to have a better spacing between the icon and the text

(this was the original [mockup](https://user-images.githubusercontent.com/2589871/109466750-79971a80-7a6a-11eb-9248-35106cbf2522.png))

**Comment by etejedor** [comment]
I subscribe @diocas comments (discussed with him in private).

**Comment by krishnan-r** [comment]
Sure yeah, 

I was going to already do some of the above, but wanted to keep the PR small, I will make another PR.

-  Can we also have a cancel button for the dialog, clicking outside doesn't feel intuitive especially when editing the project 

- Also Omar & I were thinking if we can re-use the jupyterlab codemirror code editor for the bash script box, so that we get syntax highlighting, line numbers etc.

- What are our thoughts on using https://material-ui.com/ for the components?
I did discuss briefly with Omar, it does add some incremental size to the final bundle (on first load, cached after, I have to check the exact size), but it makes some things easier, and we can use it uniformly in all the extensions. It will also be customisable for our theme and support dark theme as well, and less css to maintain, (I used it in https://github.com/swan-cern/jupyter-extensions/pull/150)

**Comment by diocas** [comment]
Yes, I saw the usage of material ui in the connector. For me is fine if we keep it consistent across all our extensions at least (and the size difference is acceptable). The other suggestions are perfect!

**Comment by omazapa** [comment]
thanks a lot for giving me a hand with this @krishnan-r

**Pull request merged**
